language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export DJANGO_SETTINGS_MODULE=sorter.test_settings
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  - flake8 sorter --ignore=E501
script:
  - coverage run --branch --source=sorter `which django-admin.py` test --settings=sorter.test_settings sorter
  - coverage report --omit=sorter/test*
env:
  - DJANGO=1.3.1
  - DJANGO=1.4
branches:
  only:
    - develop
